In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('/Users/daniehbenotman/Desktop/mena_gender_dashboard1.csv',quotechar='"')

In [4]:
df.head()

,year,value,country_name,indicator_name,unit_type
0,2000,0.0,Bahrain,A woman can apply for a passport in the same w...,Binary (1/0)
1,2000,0.0,Bahrain,"A woman can be \head of household\"" in the sam...",Binary (1/0)
2,2000,0.0,Bahrain,A woman can choose where to live in the same w...,Binary (1/0)
3,2000,0.0,Bahrain,A woman can get a job in the same way as a man...,Binary (1/0)
4,2000,0.0,Bahrain,A woman can obtain a judgment of divorce in th...,Binary (1/0)

In [5]:
df['unit_type'].unique()

array(['Binary (1/0)', 'Rate per 1,000', 'Percent (%)', 'Currency (US$)',
       'Years', 'Rate per 100,000', 'Index / Score'], dtype=object)

In [7]:
df[df['indicator_name'] == 'Prevalence of HIV, female (% ages 15-24)']

,year,value,country_name,indicator_name,unit_type
33,2000,0.1,Bahrain,"Prevalence of HIV, female (% ages 15-24)",Percent (%)
74,2001,0.1,Bahrain,"Prevalence of HIV, female (% ages 15-24)",Percent (%)
115,2002,0.1,Bahrain,"Prevalence of HIV, female (% ages 15-24)",Percent (%)
156,2003,0.1,Bahrain,"Prevalence of HIV, female (% ages 15-24)",Percent (%)
197,2004,0.1,Bahrain,"Prevalence of HIV, female (% ages 15-24)",Percent (%)
...,...,...,...,...,...
12412,2019,0.1,"Yemen, Rep.","Prevalence of HIV, female (% ages 15-24)",Percent (%)
12451,2020,0.1,"Yemen, Rep.","Prevalence of HIV, female (% ages 15-24)",Percent (%)
12490,2021,0.1,"Yemen, Rep.","Prevalence of HIV, female (% ages 15-24)",Percent (%)
12529,2022,0.1,"Yemen, Rep.","Prevalence of HIV, female (% ages 15-24)",Percent (%)
12568,2023,0.1,"Yemen, Rep.","Prevalence of HIV, female (% ages 15-24)",Percent (%)

In [5]:
df = df.applymap(lambda x:x.strip('"') if isinstance(x,str)else x)

/var/folders/ln/0dzfh__x22s4sjj8k1k2jw880000gn/T/ipykernel_2531/3691720746.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x:x.strip('"') if isinstance(x,str)else x)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12576 entries, 0 to 12575
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   year            12576 non-null  int64
 1   value           12576 non-null  float64
 2   country_name    12576 non-null  object
 3   indicator_name  12576 non-null  object
 4   unit_type       12576 non-null  object
dtypes: float64(1), int64(1), object(3)
memory usage: 491.4+ KB

In [7]:
indicator_categories = {
    # 1. Gender Rights & Legal Equality
    **{name: "Gender Rights & Legal Equality" for name in df['indicator_name'] if name.startswith("A woman")},
    "Criminal penalties or civil remedies exist for sexual harassment in employment (1=yes; 0=no)": "Gender Rights & Legal Equality",
    "Women Business and the Law Index Score (scale 1-100)": "Gender Rights & Legal Equality",

    # 2. Political Participation
    "Proportion of seats held by women in national parliaments (%)": "Political Participation",
    "Proportion of women in ministerial level positions (%)": "Political Participation",

    # 3. Fertility & Demographics
    "Adolescent fertility rate (births per 1,000 women ages 15-19)": "Fertility & Demographics",
    "Birth rate, crude (per 1,000 people)": "Fertility & Demographics",
    "Life expectancy at birth, female (years)": "Fertility & Demographics",
    "Life expectancy at birth, male (years)": "Fertility & Demographics",

    # 4. Maternal & Reproductive Health
    "Maternal mortality ratio (modeled estimate, per 100,000 live births)": "Maternal & Reproductive Health",
    "Prevalence of HIV, female (% ages 15-24)": "Maternal & Reproductive Health",
    "Prevalence of HIV, male (% ages 15-24)": "Maternal & Reproductive Health",

    # 5. Education & Literacy
    "Educational attainment, at least completed upper secondary, population 25+, female (%) (cumulative)": "Education & Literacy",
    "Educational attainment, at least completed upper secondary, population 25+, male (%) (cumulative)": "Education & Literacy",
    "Literacy rate, adult female (% of females ages 15 and above)": "Education & Literacy",
    "Literacy rate, adult male (% of males ages 15 and above)": "Education & Literacy",
    "Literacy rate, adult total (% of people ages 15 and above)": "Education & Literacy",
    "Literacy rate, youth female (% of females ages 15-24)": "Education & Literacy",
    "Literacy rate, youth male (% of males ages 15-24)": "Education & Literacy",
    "School enrollment, secondary (gross), gender parity index (GPI)": "Education & Literacy",

    # 6. Labor & Employment
    "Employment in services, female (% of female employment) (modeled ILO estimate)": "Labor & Employment",
    "Employment in services, male (% of male employment) (modeled ILO estimate)": "Labor & Employment",
    "Labor force participation rate, female (% of female population ages 15+) (modeled ILO estimate)": "Labor & Employment",
    "Labor force participation rate, male (% of male population ages 15+) (modeled ILO estimate)": "Labor & Employment",
    "Unemployment, female (% of female labor force) (modeled ILO estimate)": "Labor & Employment",
    "Unemployment, male (% of male labor force) (modeled ILO estimate)": "Labor & Employment",

    # 7. Economic Context
    "GDP per capita (current US$)": "Economic Context",
    "Inflation, consumer prices (annual %)": "Economic Context",
}

In [8]:
df['category'] = df['indicator_name'].map(indicator_categories)
df['category'] = df['category'].fillna('Other')

In [9]:
df['category'].value_counts()

category
Gender Rights & Legal Equality    4992
Education & Literacy              2280
Labor & Employment                1872
Fertility & Demographics          1248
Maternal & Reproductive Health     936
Economic Context                   624
Political Participation            624
Name: count, dtype: int64

In [10]:
df.to_csv('mena_cleaned_data1.csv',index=False)

In [11]:
df['country_name'].value_counts()

country_name
Bahrain             984
Algeria             984
Egypt, Arab Rep.    984
Iraq                984
Jordan              984
Kuwait              984
Morocco             984
Oman                984
Qatar               984
Saudi Arabia        984
Tunisia             984
Yemen, Rep.         936
Libya               816
Name: count, dtype: int64

In [12]:
region_map = {
    'Bahrain': 'GCC',
    'Kuwait': 'GCC',
    'Oman': 'GCC',
    'Qatar': 'GCC',
    'Saudi Arabia': 'GCC',

    'Egypt, Arab Rep.': 'North Africa',
    'Libya': 'North Africa',
    'Tunisia': 'North Africa',
    'Algeria': 'North Africa',
    'Morocco': 'North Africa',

    'Jordan': 'Levant',
    
    'Iraq': 'Other',
    'Yemen, Rep.': 'Other',
}

In [13]:
df['Region'] = df['country_name'].map(region_map)

In [14]:
df.to_csv('mena_cleaned_data2.csv',index=False)

In [8]:
df['indicator_name'].value_counts()

indicator_name
A woman can apply for a passport in the same way as a man (1=yes; 0=no)                                312
Maternal mortality ratio (modeled estimate, per 100,000 live births)                                   312
GDP per capita (current US$)                                                                           312
Inflation, consumer prices (annual %)                                                                  312
Labor force participation rate, female (% of female population ages 15+) (modeled ILO estimate)        312
Labor force participation rate, male (% of male population ages 15+) (modeled ILO estimate)            312
Life expectancy at birth, female (years)                                                               312
Life expectancy at birth, male (years)                                                                 312
Prevalence of HIV, female (% ages 15-24)                                                               312
Employment in services, female (% of female employment) (modeled ILO estimate)                         312
Prevalence of HIV, male (% ages 15-24)                                                                 312
Proportion of seats held by women in national parliaments (%)                                          312
Proportion of women in ministerial level positions (%)                                                 312
School enrollment, secondary (gross), gender parity index (GPI)                                        312
Unemployment, female (% of female labor force) (modeled ILO estimate)                                  312
Unemployment, male (% of male labor force) (modeled ILO estimate)                                      312
A woman can be \head of household\" in the same way as a man (1=yes; 0=no)                             312
Employment in services, male (% of male employment) (modeled ILO estimate)                             312
Women Business and the Law Index Score (scale 1-100)                                                   312
A woman can sign a contract in the same way as a man (1=yes; 0=no)                                     312
Criminal penalties or civil remedies exist for sexual harassment in employment (1=yes; 0=no)           312
Birth rate, crude (per 1,000 people)                                                                   312
Adolescent fertility rate (births per 1,000 women ages 15-19)                                          312
A woman has the same rights to remarry as a man (1=yes; 0=no)                                          312
A woman can work in an industrial job in the same way as a man (1=yes; 0=no)                           312
A woman can work in a job deemed dangerous in the same way as a man (1=yes; 0=no)                      312
A woman can work at night in the same way as a man (1=yes; 0=no)                                       312
A woman can choose where to live in the same way as a man (1=yes; 0=no)                                312
A woman can get a job in the same way as a man (1=yes; 0=no)                                           312
A woman can obtain a judgment of divorce in the same way as a man (1=yes; 0=no)                        312
A woman can open a bank account in the same way as a man (1=yes; 0=no)                                 312
A woman can register a business in the same way as a man (1=yes; 0=no)                                 312
A woman can travel outside the country in the same way as a man (1=yes; 0=no)                          312
A woman can travel outside her home in the same way as a man (1=yes; 0=no)                             312
Educational attainment, at least completed upper secondary, population 25+, male (%) (cumulative)      288
Literacy rate, youth male (% of males ages 15-24)                                                      288
Literacy rate, youth female (% of females ages 15-24)                                                  288
Educational attainment, at least completed upper secondary, population 25+, female (%) (cumulative)    288
Literacy rate, adult female (% of females ages 15 and above)                                           288
Literacy rate, adult male (% of males ages 15 and above)                                               264
Literacy rate, adult total (% of people ages 15 and above)                                             264
Name: count, dtype: int64

In [1]:
df['unit_type'].value_counts()

NameError: name 'df' is not defined