In [2]:
import os
import sys
from pathlib import Path

PROJECT_ROOT = Path(os.getcwd()).resolve()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))
os.chdir(PROJECT_ROOT)

In [5]:
print(os.getcwd())

/Users/daniehbenotman/Desktop/worldbank_tableau_project/notebooks

In [6]:
os.chdir("/Users/daniehbenotman/Desktop/worldbank_tableau_project")
print("✅ Working directory changed to:", os.getcwd())

✅ Working directory changed to: /Users/daniehbenotman/Desktop/worldbank_tableau_project

In [7]:
from pathlib import Path
print(list(Path("data").glob("*.csv")))

[PosixPath('data/DZA_selected.csv'), PosixPath('data/IND_SL.TLF.CACT.MA.ZS.csv'), PosixPath('data/MAR_raw.csv'), PosixPath('data/IND_SL.TLF.CACT.FE.ZS.csv'), PosixPath('data/KWT_raw.csv'), PosixPath('data/IND_SP.DYN.CONU.ZS.csv'), PosixPath('data/OMN_selected.csv'), PosixPath('data/QAT_raw.csv'), PosixPath('data/MAR_selected.csv'), PosixPath('data/IND_SP.DYN.CONM.ZS.csv'), PosixPath('data/all_countries_selected.csv'), PosixPath('data/IND_SH.STA.MMRT.csv'), PosixPath('data/IND_SG.IND.WORK.EQ.csv'), PosixPath('data/IND_SE.ADT.1524.LT.FE.ZS.csv'), PosixPath('data/BHR_raw.csv'), PosixPath('data/IND_SE.ADT.1524.LT.MA.ZS.csv'), PosixPath('data/KWT_selected.csv'), PosixPath('data/IND_SG.CNT.SIGN.EQ.csv'), PosixPath('data/all_countries_combined.csv'), PosixPath('data/LBY_selected.csv'), PosixPath('data/IRQ_selected.csv'), PosixPath('data/IND_SE.ENR.SECO.FM.ZS.csv'), PosixPath('data/IND_SG.HLD.HEAD.EQ.csv'), PosixPath('data/IND_SG.REM.RIGT.EQ.csv'), PosixPath('data/BHR_selected.csv'), PosixPath('data/IND_SG.GET.JOBS.EQ.csv'), PosixPath('data/IND_SG.APL.PSPT.EQ.csv'), PosixPath('data/IND_SG.GEN.PARL.ZS.csv'), PosixPath('data/IND_SG.LOC.LIVE.EQ.csv'), PosixPath('data/IND_SG.GEN.MNST.ZS.csv'), PosixPath('data/IND_SP.DYN.CBRT.IN.csv'), PosixPath('data/IND_SG.PEN.SXHR.EM.csv'), PosixPath('data/IND_SH.HIV.1524.MA.ZS.csv'), PosixPath('data/TUN_raw.csv'), PosixPath('data/IND_SH.HIV.1524.FE.ZS.csv'), PosixPath('data/IND_SG.OPN.BANK.EQ.csv'), PosixPath('data/JOR_selected.csv'), PosixPath('data/IND_SP.M15.2024.FE.ZS.csv'), PosixPath('data/IND_SE.SEC.CUAT.UP.FE.ZS.csv'), PosixPath('data/IND_SE.ADT.LITR.MA.ZS.csv'), PosixPath('data/LBY_raw.csv'), PosixPath('data/EGY_selected.csv'), PosixPath('data/SAU_selected.csv'), PosixPath('data/IND_SE.SEC.CUAT.UP.MA.ZS.csv'), PosixPath('data/IND_SE.ADT.LITR.FE.ZS.csv'), PosixPath('data/IND_FP.CPI.TOTL.ZG.csv'), PosixPath('data/IND_SG.LAW.INDX.csv'), PosixPath('data/SAU_raw.csv'), PosixPath('data/JOR_raw.csv'), PosixPath('data/IND_SL.UEM.TOTL.FE.ZS.csv'), PosixPath('data/IND_NY.GDP.PCAP.CD.csv'), PosixPath('data/IND_SP.ADO.TFRT.csv'), PosixPath('data/IND_SE.ADT.LITR.ZS.csv'), PosixPath('data/IRQ_raw.csv'), PosixPath('data/IND_SL.UEM.TOTL.MA.ZS.csv'), PosixPath('data/IND_SL.SRV.EMPL.MA.ZS.csv'), PosixPath('data/IND_SP.DYN.LE00.FE.IN.csv'), PosixPath('data/QAT_selected.csv'), PosixPath('data/YEM_raw.csv'), PosixPath('data/IND_SG.DNG.WORK.DN.EQ.csv'), PosixPath('data/IND_SP.DYN.LE00.MA.IN.csv'), PosixPath('data/IND_SL.SRV.EMPL.FE.ZS.csv'), PosixPath('data/OMN_raw.csv'), PosixPath('data/IND_SG.OBT.DVRC.EQ.csv'), PosixPath('data/IND_SP.M18.2024.FE.ZS.csv'), PosixPath('data/EGY_raw.csv'), PosixPath('data/IND_SG.CTR.TRVL.EQ.csv'), PosixPath('data/IND_SG.NGT.WORK.EQ.csv'), PosixPath('data/YEM_selected.csv'), PosixPath('data/IND_SG.BUS.REGT.EQ.csv'), PosixPath('data/IND_SG.HME.TRVL.EQ.csv'), PosixPath('data/DZA_raw.csv')]

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


plt.style.use("seaborn-v0_8-whitegrid")
sns.set_palette("viridis")
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)


df = pd.read_csv("data/all_countries_selected.csv")

df.head()

,year,value,country_id,country_name,indicator_id,indicator_name
0,2024,NaN,BH,Bahrain,SG.APL.PSPT.EQ,A woman can apply for a passport in the same w...
1,2023,1.0,BH,Bahrain,SG.APL.PSPT.EQ,A woman can apply for a passport in the same w...
2,2022,1.0,BH,Bahrain,SG.APL.PSPT.EQ,A woman can apply for a passport in the same w...
3,2021,1.0,BH,Bahrain,SG.APL.PSPT.EQ,A woman can apply for a passport in the same w...
4,2020,1.0,BH,Bahrain,SG.APL.PSPT.EQ,A woman can apply for a passport in the same w...

In [10]:
df.rename(columns={"year":"Year","value":"Value","country_name":"Country","indicator_id":"Indicator Code","indicator_name":"Indicator"},inplace=True)

In [12]:
df.rename(columns={"country_id":"Country Code"},inplace=True)

In [19]:
df.drop(columns={"Country Code"},inplace=True)

In [21]:
df.head()

,Year,Value,Country,Indicator Code,Indicator
0,2024,NaN,Bahrain,SG.APL.PSPT.EQ,A woman can apply for a passport in the same w...
1,2023,1.0,Bahrain,SG.APL.PSPT.EQ,A woman can apply for a passport in the same w...
2,2022,1.0,Bahrain,SG.APL.PSPT.EQ,A woman can apply for a passport in the same w...
3,2021,1.0,Bahrain,SG.APL.PSPT.EQ,A woman can apply for a passport in the same w...
4,2020,1.0,Bahrain,SG.APL.PSPT.EQ,A woman can apply for a passport in the same w...

In [22]:
columns_order = ['Country', 'Year', 'Indicator Code', 'Indicator', 'Value']
df = df[columns_order]

In [23]:
df.head()

,Country,Year,Indicator Code,Indicator,Value
0,Bahrain,2024,SG.APL.PSPT.EQ,A woman can apply for a passport in the same w...,NaN
1,Bahrain,2023,SG.APL.PSPT.EQ,A woman can apply for a passport in the same w...,1.0
2,Bahrain,2022,SG.APL.PSPT.EQ,A woman can apply for a passport in the same w...,1.0
3,Bahrain,2021,SG.APL.PSPT.EQ,A woman can apply for a passport in the same w...,1.0
4,Bahrain,2020,SG.APL.PSPT.EQ,A woman can apply for a passport in the same w...,1.0

In [18]:
df.duplicated().sum()

175500

In [9]:
df.isna().sum()

year                  0
value             47073
country_id            0
country_name          0
indicator_id          0
indicator_name        0
dtype: int64

In [14]:
empty_indicators = (
    df.groupby("Indicator Code")["Value"]
    .apply(lambda x: x.isna().all())
)

# Filter only True (completely missing indicators)
empty_indicators = empty_indicators[empty_indicators].index.tolist()

print(f"Indicators with no data: {len(empty_indicators)}")
print(empty_indicators[:10])

Indicators with no data: 0
[]

In [1]:
df["Value"].isna().sum(), df["Value"].isna().mean()

NameError: name 'df' is not defined